### ISSUE TITLE
Colour Match: Color parameter outside of the expected range: Alpha

### ISSUE THREAD

**Issue by jwaes** [SonarSonic/DrawingBotV3#105]
When choosing 'color match' as a colour seperation. I get a 'Color parameter outside of expected range: Alpha' error with the default settings. 

![image](https://github.com/SonarSonic/DrawingBotV3/assets/50528773/10592e57-db12-49ff-9de4-3414ddbb9997)

When i 'configure' and lower the brightness multiplier substantially it will go through and result in an output.

I would expec the 'default' settings to give 'some' results.

1.6.6 Beta Premium

**Comment by SonarSonic** [comment]
Fixed in v1.6.7
