### ISSUE TITLE
processing  video frames while exporting to vpype

### ISSUE THREAD

**Issue by WILLARDKLEIN** [SonarSonic/DrawingBotV3#109]
I'm not sure if this is a bug or an unsupported feature but when processing a video file and trying to have it export with vpype it yields no exported svg or even able to use the show feature of vpype.

**To Reproduce**
import video file
and export to vpype 

**Expected behavior**
batch frame exporting from video similar to the export SVG feature 

**DrawingBotV3 Version**
(e.g. v1.6.9-Premium

**Operating System**
Windows 10

**Comment by SonarSonic** [comment]
I haven't implemented support for Video -> VPype, I will add support in a future version.
