### ISSUE TITLE
CMYK Notably worse on 1.6.9 Beta vs 1.6.3 Beta

### ISSUE THREAD

**Issue by Wyth** [SonarSonic/DrawingBotV3#111]
Using the same options for adaptive stippling and default CMYK color separation. Only changes made are to the opacity of the pens, and the blending mode to 'darken'.

![image](https://github.com/SonarSonic/DrawingBotV3/assets/3047136/406b741d-0e5f-4496-95db-32b7a18a3e0a)

**Comment by SonarSonic** [comment]
Do you get the same result if you set Clean Black / Clean White to 0?

**Comment by Wyth** [comment]
That actually does improve it quite a bit. Setting the Clean Black / Clean White to 0 makes the resulting image much closer to the previous versions, and quite a bit better. Not quite as good (in my opinion as the previous versions, but much more usable now. I'd suggest maybe making the default 0?

**Comment by SonarSonic** [comment]
I will most likely change the defaults, you can also configure the default values in preferences.
