### ISSUE TITLE
Open line in gcode after export

### ISSUE THREAD

**Issue by cojarbi** [SonarSonic/DrawingBotV3#113]
Im not sure this is a bug but i could note find any setting to adjust this.

As seen on the attachment, after exporting gcode, you can see the beginning/end of path that results in the segment not overlapping. creating a gap.

![SCR-20231128-gija](https://github.com/SonarSonic/DrawingBotV3/assets/16444438/69eb52d4-2cc4-4417-abcb-4ed98b0486e0)

**Comment by SonarSonic** [comment]
That does look like a bug dealing with closed paths, could you send me the SVG?

**Comment by cojarbi** [comment]
Sure, here you go

![3Youtube_logo_plotted_1_pens1_to_1](https://github.com/SonarSonic/DrawingBotV3/assets/16444438/97f537ba-30bc-413f-92ce-b75acde0d755)

**Comment by SonarSonic** [comment]
Have you tried plotting with the file as is? I've looked at GCode from DBV3 and there is no issue, the paths are exported as I'd expect. It actually looks like it could be a rendering issue in the other software, or a parsing issue, as it will does the moves needed but is showing them in yellow instead of red.

**Comment by cojarbi** [comment]
Yes, please see attached

![IMG_3526](https://github.com/SonarSonic/DrawingBotV3/assets/16444438/d2f9087a-e26f-46a7-9dc7-a0d5e127142c)

**Comment by SonarSonic** [comment]
I looks like the plotter needs calibration, most of the lines don't look accurate to me. Some lines seem to bend away before reaching the end, maybe the plotter is running too fast and is slipping.

**Comment by cojarbi** [comment]
Noted, after checking, there was a slight difference on squareness. 

Thanks

I will close this one
