### ISSUE TITLE
SVG Converter Ignoring Crosshatch

### ISSUE THREAD

**Issue by zenmechanical** [SonarSonic/DrawingBotV3#115]
**Describe the bug**
When using the SVG Convertor it ignores the crosshatch checkbox and will crosshatch each time or add a diagonal hatch throughout. 

**To Reproduce**
1. Import SVG
2. Uncheck Shape Clipping, Derive Drawing Set, Link Ends, Crossharch
3. Same issue if using default or color match in the Colour Separation field under pen settings
4. See result

**DrawingBotV3 Version**
(e.g. v1.6.101 alpha)

**Operating System**
Windows 10

**Additional info**

**Comment by SonarSonic** [comment]
Should be fixed in v1.6.10, if not re-open this issue and please send me the SVGs that are still failing
