### ISSUE TITLE
HPGL ESC commands

### ISSUE THREAD

**Issue by ilachEU** [SonarSonic/DrawingBotV3#121]
**Is your feature request related to a problem? Please describe.**
My HPGL plotter requires sending several ESC commands before the actual drawing to work correctly with DrawingBotV3 

**Describe the solution you'd like**
In the HPGL setup window, add the ability to set the HPGL start sequence, including the ability to specify ESC characters

**Describe alternatives you've considered**
I now have a separately made HPGL file with the start sequence that I have to send to plotter before the actual drawing

**Comment by SonarSonic** [comment]
I will introduce this for you in a future version as I've received similar requests. What HPGL plotter is it out of interest?

**Comment by ilachEU** [comment]
Aritma Colorgraf 0512

**Comment by SonarSonic** [comment]
Added in v1.6.14
