### ISSUE TITLE
Hatch Sawtooth PFM does not work when used within Mosaic Segments

### ISSUE THREAD

**Issue by BrianEaton4** [SonarSonic/DrawingBotV3#122]
**Describe the bug**
When using Mosaic Segments, the Hatch Sawtooth PFM does not work and produces gaps.

**DrawingBotV3 Version**
v1.6.13-Premium

**Operating System**
Mac M1 Pro

**Additional info**
It's saying the file is too big to upload here, so here it is on my Google Drive: https://drive.google.com/drive/folders/1GxzLgByJnECHY7zPQURn1RGWUftJ5YGD?usp=sharing

<img width="1683" alt="Screenshot 2024-02-27 at 7 08 49 PM" src="https://github.com/SonarSonic/DrawingBotV3/assets/161539007/82272b8e-4a4b-4b92-ae51-bde23c1eda91">

**Comment by SonarSonic** [comment]
Fixed in v1.6.14
