### ISSUE TITLE
Menus and modals do not render properly on Ubuntu Regolith (i3 tiling window manager)

### ISSUE THREAD

**Issue by falko-apheris** [SonarSonic/DrawingBotV3#124]
**Describe the bug**
- The top menu bar can not be opened with a mouse since the dropdown appears like 20 px below the button and disappears immediately when the mouse moves into the gap between the button and the dropdown.
- modals appear very small in height and can not be resized

see attached images 

On the regular Ubuntu desktop manager everything works just fine.

**To Reproduce**
Start the app in a i3 tiling window manager.

**Expected behavior**
Menus and modals render like on regular Ubuntu desktop manager

**Screenshots**
![Screenshot from 2024-03-01 09-23-41](https://github.com/SonarSonic/DrawingBotV3/assets/86360866/4e3578a3-22c9-4320-a1a6-236d687325e7)
![Screenshot from 2024-03-04 11-10-28](https://github.com/SonarSonic/DrawingBotV3/assets/86360866/014dee57-1385-4ff2-9ba4-529827e9a109)

**DrawingBotV3 Version**
v1.6.13-stable-free

**Operating System**
Ubuntu 22.04.4 LTS with Regolith 2 https://regolith-desktop.com/

**Comment by falko-apheris** [comment]
https://www.reddit.com/r/i3wm/comments/jzciw9/wrong_menu_position_on_any_javafx_application/ this is exactly the problem
I have the feeling the modal issue could be fixed by allowing resizing of the modal.

**Comment by SonarSonic** [comment]
The JDK team have pushed a fix to a newer version of JavaFX, I will be update to that and hopefully it will be resolved! https://bugs.openjdk.org/browse/JDK-8251240

**Comment by select** [comment]
I tried it on the new alpha. It's solve :heart:

**Comment by falko-apheris** [comment]
![Screenshot from 2024-03-18 09-52-21](https://github.com/SonarSonic/DrawingBotV3/assets/86360866/1770e728-9b60-42bf-81eb-687c0c3222c3)
