### ISSUE TITLE
Menus don't resize properly, inputs not readable, unnecessary scrollbars

### ISSUE THREAD

**Issue by select** [SonarSonic/DrawingBotV3#129]
**Describe the bug**
Text is hidden on the button, buttons can not be read. Resizing the menu does not resize the button. See screenshot

**To Reproduce**
Resize menus like in the screenshots

**Expected behavior**
Buttons and other inputs become readable

**Screenshots**
The text is not readable on the inputs even though there is enough space, I'm not even sure what it should say on the `E...` button
![Screenshot from 2024-03-08 15-37-40](https://github.com/SonarSonic/DrawingBotV3/assets/1164760/1f955345-6efd-46bb-9c92-dce8410ed660)

Not all controls are visible since the section does not resize properly, very annoying scrollbars.
There is a totally redundant scrollbar on the right that only scrolls a few pixels
![Screenshot from 2024-03-08 15-40-01](https://github.com/SonarSonic/DrawingBotV3/assets/1164760/2868b5f0-d862-462a-b847-1daab95eab35)

**DrawingBotV3 Version**
DrawingBotV3-Premium-1.6.13-stable-linux.deb

**Operating System**
Ubuntu 22.04.4 LTS

**Additional info**
(Add any other info about the problem here.)

**Comment by SonarSonic** [comment]
Some of this issue is caused by a different default font size on Linux vs Windows. Once I'm able to properly test on Linux I'll make some changes.
