### ISSUE TITLE
Batch Processing 'sourceImage' is null

### ISSUE THREAD

**Issue by paul-ferragut** [SonarSonic/DrawingBotV3#152]
**Describe the bug**
batch processing not working anymore
'Batch processing - java.lang.NullPointerException: Cannot invoke 'java.awt.image.BufferedImage.getWidth()' because 'sourceImage' is null
I have a folder with png images

**To Reproduce**
1. Link input and output folder
2. Click on 'Start Batch Processing'

**Expected behavior**
Process images and export

**Screenshots**

**DrawingBotV3 Version**
v1.6.20-Premium

**Operating System**
Windows

![Screenshot 2024-11-13 232645](https://github.com/user-attachments/assets/5f4c1c68-ff84-48c3-9ee0-2b4060cfa2a0)

**Comment by SonarSonic** [comment]
Fixed in v1.6.21-stable, which is out now!

**Comment by paul-ferragut** [comment]
It works, Thanks!!
