### ISSUE TITLE
Adjust brightness feature in Sketch pathfinding

### ISSUE THREAD

**Issue by paul-ferragut** [SonarSonic/DrawingBotV3#154]
Hi
I am interested in single pen plot and I watch this tutorial:
https://www.youtube.com/watch?v=bdJ8aZUJX5U
However I don't see the feature adjust brightness showed at 0:55
https://youtu.be/bdJ8aZUJX5U?si=DFR5Ko3gmvlOcDeu&t=55
Is there a replacement for this feature?
thanks!

**Comment by SonarSonic** [comment]
Hello!

Adjust brightness was replaced with Erase Min/Max in v1.5.2-beta. Here is an extract from the change log which explains the change.

- Added: **New Erasing Settings for Sketch PFMS**, these allow the creation of new styles, specifically ones which can be drawn more easily with a single pen. The following settings have been added.
  These settings replace "Adjust Brightness", you can think of "Erase Min" and "Erase Max" as the "Adjust Brightness range", using the same erase min & max is the same as setting "Adjust Brightness" in previous versions.
  Using a Erase Radius Min & Erase Radius Max of 1.0 will produce the same results as previous versions. The radius allows you to control the spacing of lines in a way which wasn't possible before.
  - Erase Min: the minimum intensity of the erase process
  - Erase Max: the maximum intensity of the erase process
  - Erase Radius Min: the minimum radius of the erased shape
  - Erase Radius Max: the maximum radius of the erased shape
  - Tone: controls the contrast of the erase processs, using a higher Tone will result in a image with a stronger contrast in the spacing of lines. The tone slider has no effect when the Erase Range values are identical.
