### ISSUE TITLE
Drawing vs. canvas alignment

### ISSUE THREAD

**Issue by HanzPetrov** [SonarSonic/DrawingBotV3#18]
Hi Ollie,

Although only really noticeable when working with small drawing sizes, the drawing and canvas appear to be misaligned.  I suspect that this has something to do with stroke coordinates vs. pixel coordinates (corner vs. centre of pixel) - and it may be desired behaviour - but my WYSIWYG expectation would be to have stroke start and end points aligned with pixel centres.

Observed:
![Observed](https://user-images.githubusercontent.com/1171023/139740061-3424ceed-98e5-4115-8a51-fcd120ae6ea1.png)

Expected:
![Expected](https://user-images.githubusercontent.com/1171023/139740036-54906e25-435c-4c9c-aba5-fe49cc65ba9d.png)

I have kluged a fix (based on the idea that the misalignment is always equal to one-half pixel), but will hold off on a PR, since this might throw off GCode expections, or have other unintended consequences.  Any thoughts welcome.
![commit](https://user-images.githubusercontent.com/1171023/139740123-3d8e7df1-887a-435f-a290-b7110cbdfeb3.png)

PS. Brilliant work refactoring Scott’s code, developing an elegant GUI, and adding loads of great new features and PFMs!

**Comment by SonarSonic** [comment]
Hello!
Thanks for your work and for spotting this!
I added some thoughts to your commits :)
