### ISSUE TITLE
Please add rendering SVG

### ISSUE THREAD

**Issue by smmsamm** [SonarSonic/DrawingBotV3#26]
Hi,
Your App can make animation and Import SVG
There is animation svg But there is not any software that can convert animation SVG to Mp4
Please Add this feature:
Converting animation SVG to video.

**Comment by SonarSonic** [comment]
I think this is out of the scope of DrawingBotV3.
Seems like there may already be ways to do this too.
https://stackoverflow.com/questions/7818670/inkscape-animated-svg-to-video
