### ISSUE TITLE
Add vpype-flow-imager New Path Finding

### ISSUE THREAD

**Issue by DrQuiet** [SonarSonic/DrawingBotV3#28]
Hi, i don't know if it's possible, but vpype-flow-imager path finding looks really great, but it's not easy to use like DrawingBot.
If you can integrate this Path Finding, it can be nice

Thnks for you works

https://github.com/serycjon/vpype-flow-imager

**Comment by SonarSonic** [comment]
Added my own implementation of this style in v1.6.10!
![streamlines_preset_fingerprints](https://github.com/SonarSonic/DrawingBotV3/assets/10425594/d721ea30-c8a4-4eba-ae6b-8cd891880bc4)
