### ISSUE TITLE
GCode placement issue: offsets and negative margins

### ISSUE THREAD

**Issue by reven** [SonarSonic/DrawingBotV3#4]
Ollie, the extra options for GCode are awesome! It's nice to set axis rotation and have personalized start, end, etc.

But unless I'm missing something, I still can't place files effectively; I can get there in the end by trial and error just using arbitrary offsets. Here is a default GCode for an XY printer with origin in the lower left corner:

![gcode(pos)(pos)](https://user-images.githubusercontent.com/206993/114142001-36309700-98c7-11eb-8b41-7f38b664bcac.jpg)

It mirrors Y but respects the offsets (in this case 45 for X and 30 for Y). Changing the Y axis to negative generates this GCode:

![gcode(pos)(neg)](https://user-images.githubusercontent.com/206993/114142146-65470880-98c7-11eb-917a-d81fa14c6c5e.jpg)

So now the image is right side up, but it's out of the bed. To get it back in I have to set an arbitrary Y offset of -330:

![gcode(pos)(neg_neg_offset)](https://user-images.githubusercontent.com/206993/114142536-eb634f00-98c7-11eb-9347-243286351032.jpg)

Arbitrary because it depends on the height of the image, not the print bed, so it'll be different each time. And also for some reason this causes the X offset to change (I think?)

I don't know of any printers that take negative values for their axis, independently of their origin, so wouldn't it be possible to instead of making the values negative or positive, just mark the origin corner and generate positive values?

I don't know on what other machines people use DrawingBot, so the way it is right now may be useful for them.

**Comment by SonarSonic** [comment]
Additional ones to fix when re-visiting g-code export.
- Drawing not being centred
- Check CMYK plots all have the same centre.

**Comment by SonarSonic** [comment]
@reven What slicer are you using to preview the gcode?

**Comment by reven** [comment]
> @reven What slicer are you using to preview the gcode?

Repetier host, though you have to mark the option to see movements.

**Comment by SonarSonic** [comment]
@reven Let me know how you get on with the new version I've just released, hopefully it should fix all the issues mentioned above :)

**Comment by reven** [comment]
Thanks @SonarSonic !!

Sorry I didn't get back to you sooner. I just did some export tests and the generated gcode seems perfect. Offsets are spot on, and everything looks good.
