### ISSUE TITLE
Layers PFM does not honour the Flip Horizontal/Vertical settings

### ISSUE THREAD

**Issue by led** [SonarSonic/DrawingBotV3#49]
### DESCRIPTION:
Flipping an image horizontally or vertically in the 'Image Processing' section appears to be ignored when using the 'Layers PFM'.

### EXPECTED:
Using the Layers PFM would render the image in the same way as the other PFMs with respect to the Image Processing options.

### REPRODUCE:
Import and image, set 'Flip Horizontal' in the 'Image Processing' pane. Then choose the 'Layers PFM', add your PFMs of choice and render. The image won't be flipped.

### VERSION:
v1.3.6-alpha, Mac

**Comment by SonarSonic** [comment]
Fixed in dev.
