### ISSUE TITLE
add controls for option sliders

### ISSUE THREAD

**Issue by zxsq-cc** [SonarSonic/DrawingBotV3#5]
feature request: add arrows or the ability to type a specific value to option sliders, e.g. dirty border>type

**Comment by SonarSonic** [comment]
Is this specifically for Image Filter options? And primarily in the option window or in the table which lists the filters?

**Comment by zxsq-cc** [comment]
yes e.g. 
![image](https://user-images.githubusercontent.com/44452124/114575922-a5501780-9c48-11eb-971c-33a7e826e841.png) can't click/type numbers here
