### ISSUE TITLE
Suggestions/Improvements for Adaptive Circular Scribbles

### ISSUE THREAD

**Issue by SonarSonic** [SonarSonic/DrawingBotV3#50]
As per email suggestion.
![output_image 19095](https://user-images.githubusercontent.com/10425594/158038704-f8c29571-fff0-43d8-a6ff-a269b74d890f.png)

**Comment by papiend** [comment]
It would be great if thescribbler could output a path in .svg so that it could be used in a drawing machine.
If anyone could help, I would be grateful forever. 

[](http://3dstereophoto.blogspot.com/2019/04/painting-software-scribbler.html)

**Comment by papiend** [comment]
[http://3dstereophoto.blogspot.com/2019/04/painting-software-scribbler.html](url)

**Comment by SterkArtLine** [comment]
@papiend  Yes, we are in the same situation. I've searched too, but someone with good coding knowledge needs help. I hope a solution is found.

**Comment by SonarSonic** [comment]
![single_path](https://user-images.githubusercontent.com/10425594/163738062-4a8d211d-71c2-4c3c-bdb2-5e211b7934c1.jpg)

I'm working on it ;)

**Comment by SterkArtLine** [comment]
You're amazing Ollie, I'm so glad to see this message.  It was exactly the algorithm and drawing style I needed to “create gradations without multiple pencils”.  I'm counting on you good luck :)

**Comment by led** [comment]
This looks fabulous. Itching to give it a 'whirl'.

**Comment by papiend** [comment]
https://www.youtube.com/watch?v=vxjM5HyqyUI&list=PLmm_L3InpMwE6SbfY1IE17f0Zcmc-WbGd&index=3

Maybe this is where you can get an idea ...

**Comment by SonarSonic** [comment]
![circular_scribbles_final](https://user-images.githubusercontent.com/10425594/164569781-6329315b-3f68-4750-9f6e-ab6bf9af0bd3.jpg)

**Comment by SterkArtLine** [comment]
The option to have lines only in the portrait, without the lines in the background like other filters in DrawingBot software, would be great.

**Comment by SonarSonic** [comment]
@SterkArtLine This isn't the final version of the Path Finding Module, I'm trying to get it as close as possible to the paper [_Tone- and Feature-Aware Circular Scribble Art_](https://www.researchgate.net/publication/282940942_Tone-_and_Feature-Aware_Circular_Scribble_Art) as possible currently and in their implementation they don't limit the curve areas in white areas of the image as this can lead to artifacts. I do think it will be possible though, but it may be that it only works really well on images like he one above, where there is a clear subject.

**Comment by SonarSonic** [comment]
I'll reopen this issue actually as an for enhancements to the Algorithm

- [ ] Option to prevent the curves from drawing over white areas of the image.

**Comment by SterkArtLine** [comment]
![portrait circular](https://user-images.githubusercontent.com/102038329/164718248-67d279c9-3701-45c1-be41-dbbc9ecc7209.jpg)

Here is an example of a picture I drew with the ChiuEtAl algorithm earlier. There are no lines in the white areas. It's the same thing we're talking about. I eagerly await the results. I hope it ends soon, Ollie. I wish you ease.

**Comment by SonarSonic** [comment]
Yeah that's style is the aim. Where can I find this implementation of the Algorithm to compare results?

**Comment by SonarSonic** [comment]
Ahh I found it. I've been coding mine from scratch, I shall make some comparisons.

**Comment by SterkArtLine** [comment]
Well, I can send the file if you need it.

**Comment by SterkArtLine** [comment]
Ollie Lansdell ***@***.***>, 22 Nis 2022 Cum, 16:42 tarihinde
şunu yazdı:

**Comment by SonarSonic** [comment]
Just an update to say this algorithm was added in the latest version, you should use image with a high resolution and very high contrast for the best results and if you wish to achieve results similar to Chiu Et Al’s implementation use a size of paper, pen width which gives you a plotting size of 4000px on the largest edge then use the “Chiu Et Al – 4000px” preset.

**Comment by papiend** [comment]
![Andrea-removebg](https://user-images.githubusercontent.com/46861622/196365797-62a0848a-3ddf-47d2-ad5c-92c056e564fe.jpg)

**Comment by led** [comment]
To fix the pen lift issue, set your clipping mode to 'Page' (you'll find it in the 'Drawing Area' panel). You might need to make sure you've got a slight margin around your image too.

**Comment by SonarSonic** [comment]
Closing as Adaptive Circular Scribbles is out of Beta as of v1.5.2 and producing really lovely results!
