### ISSUE TITLE
CMYK processing can't be stopped

### ISSUE THREAD

**Issue by led** [SonarSonic/DrawingBotV3#60]
**Describe the bug**
Once the 'Start' button is pressed to process an image in CMYK mode, the 'Stop' button appears to have no effect.

**To Reproduce**
1. Setup and image
2. Set 'Colour Separation' to 'CMYK'
3. Click 'Start' button
4. Click 'Stop' button. 

**Expected behavior**
Expected to be able abort the processing as with the other Colour Separation modes.

**DrawingBotV3 Version**
1.4.0 Premium

**Operating System**
Mac Intel

**Comment by SonarSonic** [comment]
Fixed in dev
