### ISSUE TITLE
Extra pen in Staedtler Fineliner 334 - 36 x Pen Set

### ISSUE THREAD

**Issue by mariana-s-fernandes** [SonarSonic/DrawingBotV3#69]
**Describe the bug**
The pen 222 is being included in the Staedtler Fineliner 334 - 36 x Pen Set but it's should not be. I have this set of pens so I have checked. All of the others are ok.

**DrawingBotV3 Version**
v1.4.1-Premium.exe

**Operating System**
Windows

**Comment by led** [comment]
Good catch!
