### ISSUE TITLE
Editing a text control item in the left-hand panel and pressing return sets panel scroll position to the top.

### ISSUE THREAD

**Issue by led** [SonarSonic/DrawingBotV3#76]
**The bug**
Editing a text control item in the left-hand panel and pressing return sets panel scroll position to the top, losing the current scroll position etc.

**To Reproduce**
1. Edit a field item, eg a pen's weight value.
2. Hit return to confirm the edit.
3. See the lhs panel's scroll position reset to the top.

**Expected behavior**
The scroll position doesn't change.

**DrawingBotV3 Version**
All current versions.

**Operating System**
Mac

**Comment by SonarSonic** [comment]
Unable to re-create in v1.5.2. Closing for now
