### ISSUE TITLE
Masks are always displayed

### ISSUE THREAD

**Issue by rachase** [SonarSonic/DrawingBotV3#83]
**Describe the bug**
On Ubuntu 20.04, svg based masks are always shown, making it hard to see the drawing output

**To Reproduce**
1. Load an image.
2. Add a few svg based masks.
3. Toggle the show masks button.
4. Masks stay visible. 

**DrawingBotV3 Version**
1.5.1 Premium 

**Operating System**
Linux

**Comment by SonarSonic** [comment]
Fixed in v1.5.2
