### ISSUE TITLE
Export image as png colour issue

### ISSUE THREAD

**Issue by led** [SonarSonic/DrawingBotV3#93]
**Image File exports in PNG format with all black lines**
No colour appears to be exported when choosing the PNG format, just a B/W version of the render.

**To Reproduce**
Render a plot, 'File->Export per/Drawing->Image FIle, select PNG format, save.

**Expected behavior**
The same colour image as is exported for JPEG, TIFF etc.

**DrawingBotV3 Version**
v1.6.2 Premium

**Operating System**
MacOS

![SCR-20230726-mogj](https://github.com/SonarSonic/DrawingBotV3/assets/395440/22737176-5ac6-4c69-a729-f27a6e8ceb76)

**Comment by SonarSonic** [comment]
Do you have any Blend Mode enabled and do you have "Export Transparent PNGs" enabled?

**Comment by led** [comment]
Yes, transparent is set, and I usually have blend mode set (multiply/darkness). Can now confirm that colours are saved when either…

- no blend mode but transparent still set.
- blend mode and transparency is turned off.
